# Generated by Django 4.1.5 on 2023-02-16 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SqlGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('parent_groups', models.ManyToManyField(blank=True, to='inventory.sqlgroup')),
            ],
        ),
        migrations.CreateModel(
            name='SqlSecret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('enable', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SqlHost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255)),
                ('host', models.CharField(max_length=255)),
                ('port', models.PositiveIntegerField(default=22)),
                ('platform', models.CharField(choices=[('IOS', 'cisco_ios'), ('ASA', 'cisco_asa'), ('NXOS', 'cisco_nxos'), ('JUNOS', 'juniper_junos'), ('SCREENOS', 'juniper_screenos')], default='IOS', max_length=30)),
                ('transport', models.CharField(choices=[('TELNET', 'telnet'), ('SSH', 'ssh'), ('HTTP', 'http'), ('HTTPS', 'https')], default='SSH', max_length=10)),
                ('site', models.CharField(blank=True, max_length=255)),
                ('type', models.CharField(blank=True, max_length=255)),
                ('groups', models.ManyToManyField(blank=True, to='inventory.sqlgroup')),
                ('secret', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.sqlsecret')),
            ],
        ),
    ]
